id: page-directory-list
title: Implement directory-list page
layers: ["interface"]
tags: ["page", "frontend", "route", "seo"]
spec_refs: ["spec:pages.directory-list", "spec:sitemap.directory-list"]
needs:
  - layout-base
  - layout-public
  - component-directory-list
checklist:
  - Page route /directory implemented in src/pages/directory/index.astro
  - Layouts integrated in rendering order: base, public
  - Query logic wired via server actions for q_all, q_subunit, q_partner, q_ngo, q_parent
  - Shared component component-directory-list used
  - ACL visibility respected (public)
  - SEO metadata present from spec
