id: page-procurement
title: Implement procurement page
layers: ["interface"]
tags: ["page", "frontend", "route", "seo"]
spec_refs: ["spec:pages.procurement", "spec:sitemap.procurement"]
needs:
  - layout-base
  - layout-public
  - component-procurement-list
checklist:
  - Page route /procurement implemented in src/pages/procurement/index.astro
  - Layouts integrated in rendering order: base, public
  - Query logic wired via server actions for q_open, q_closed
  - Shared component component-procurement-list used
  - ACL visibility respected (public)
  - SEO metadata present from spec
