id: page-contact
title: Implement contact page
layers: ["interface"]
tags: ["page", "frontend", "route", "seo"]
spec_refs: ["spec:pages.contact", "spec:sitemap.contact"]
needs:
  - layout-base
  - layout-public
checklist:
  - Page route /contact implemented in src/pages/contact.astro
  - Layouts integrated in rendering order: base, public
  - Query logic wired via server actions for q_settings
  - ACL visibility respected (public)
  - SEO metadata present from spec
