id: page-admin-procurement
title: Implement admin-procurement page
layers: ["interface"]
tags: ["page", "frontend", "route"]
spec_refs: ["spec:pages.admin-procurement", "spec:sitemap.admin-procurement"]
needs:
  - layout-base
  - layout-admin
  - action-procurement-create_proc
  - action-procurement-update_proc
  - action-procurement-publish_proc
  - component-procurement-list
checklist:
  - Page route /admin/procurement implemented in src/pages/admin/procurement.astro
  - Layouts integrated in rendering order: base, admin
  - Query logic wired via server actions for q_list
  - Mutation logic wired via server actions for create_proc, update_proc, publish_proc
  - Shared component component-procurement-list used
  - ACL visibility respected (authenticated)
  - No SEO metadata (admin page)
