id: page-home
title: Implement home page
layers: ["interface"]
tags: ["page", "frontend", "route", "seo"]
spec_refs: ["spec:pages.home", "spec:sitemap.home"]
needs:
  - layout-base
  - layout-public
  - component-announcements-list
  - component-news-list
  - component-procurement-list
  - component-directory-list
checklist:
  - Page route / implemented in src/pages/index.astro
  - Layouts integrated in rendering order: base, public
  - Query logic wired via server actions for q_settings, q_recent_ann, q_recent_news, q_open_proc, q_commander, q_parent_dir
  - Shared components component-announcements-list, component-news-list, component-procurement-list, component-directory-list used
  - ACL visibility respected (public)
  - SEO metadata present from q_settings and spec
