id: action-procurement-update_proc
feature: procurement
layers:
  - application
tags:
  - server-action
  - validation
  - db-access
  - auth
spec_refs:
  - pages.admin-procurement.actions.update_proc
needs:
  - cm-schema
done_checklist:
  - Function exists in src/actions/procurement/action.ts
  - Input schema validated using Zod from src/actions/procurement/schema.ts
  - ACL enforced for authenticated users
  - Database write performed for procurement entity
  - Revalidation triggered for /procurement
  - Errors handled appropriately
